FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE "dummy.settings"

# ENV OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED true
# ENV OTEL_TRACES_EXPORTER otlp
# ENV OTEL_EXPORTER_OTLP_ENDPOINT http://localhost:4317
# ENV OTEL_EXPORTER_OTLP_INSECURE true

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
# RUN opentelemetry-bootstrap -a install


# Copy the application files
COPY dummy/ /app/

# run migrations and other setup stuff
RUN python manage.py makemigrations
RUN python manage.py migrate

VOLUME [ "/app" ]

# Expose the port the app runs on
EXPOSE 8088

# Start the application
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8088"]
# CMD [ "opentelemetry-instrument", "--traces_exporter", "console", "--metrics_exporter", "console", "--logs_exporter", "console", "--service_name", "dice-server", "python", "manage.py", "runserver", "0.0.0.0:8088"]
# CMD [ "opentelemetry-instrument", "python", "manage.py", "runserver", "0.0.0.0:8088"]
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8088", "--noreload"]





